name: Update Corona Charts

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  # This will run at 7:30 and 16:30
  schedule:
    - cron: "30 5,14 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bots/corona-charts/
    steps:
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.2"
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R/renv
          key: ${{ runner.os }}-r-4.2.2-renv-${{ hashFiles('./bots/corona-charts/renv.lock') }}
      - name: Restore R packages
        run: |
          install.packages("renv")
          renv::activate()
          renv::restore()
        shell: Rscript {0}
      - name: Run R scripts
        run: |
          Rscript corona-auto-ch/corona-auto-ch.R
        #  Rscript owid_vaccinations_worldwide/owid_vaccinations_worldwide.R
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install node packages
        run: npm install -g @nzz/q-cli
      - name: Run Q cli
        run: Q update-item
        env:
          Q_PRODUCTION_SERVER: ${{ secrets.Q_PRODUCTION_SERVER }}
          Q_PRODUCTION_ACCESSTOKEN: ${{ secrets.Q_PRODUCTION_ACCESSTOKEN }}
      - name: Log failure to slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
