name: Update Stock market Charts

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  # This will run it at 7:45 and 23:45.
  schedule:
    - cron: "45 5,9,13,17,21 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: bots/stock-market/
    steps:
      - uses: actions/checkout@v3
 #     - name: Setup R
 #       uses: r-lib/actions/setup-r@v1
 #       with:
 #         r-version: "4.0.5"
 #     - name: Install system dependencies
 #       run: |
 #         sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
 #     - name: Cache R packages
 #       uses: actions/cache@v2
 #       with:
 #         path: ~/.cache/R/renv
 #         key: ${{ runner.os }}-r-4.0.5-renv-${{ hashFiles('./bots/stock-market/renv.lock') }}
 #     - name: Restore R packages
 #       run: |
 #         install.packages("renv")
 #         renv::activate()
 #         renv::restore()
 #       shell: Rscript {0}
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >>$GITHUB_OUTPUT
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('./bots/stock-market/requirements.txt') }}
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run python scripts
        run: |
          python economic_indicators.py
          git pull
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: :!*.json
          commit_message: Upload csvs with prices
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install node packages
        run: npm install -g @nzz/q-cli
      - name: Run Q cli
        run: Q update-item
        env:
          Q_PRODUCTION_SERVER: ${{ secrets.Q_PRODUCTION_SERVER }}
          Q_PRODUCTION_ACCESSTOKEN: ${{ secrets.Q_PRODUCTION_ACCESSTOKEN }}
      - name: Log failure to slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
         status: ${{ job.status }}
         notify_when: "failure"
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
