name: Update Travel Guide

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  # This will run at 4am and 4pm (CEST)
  schedule:
    - cron: "0 2,14 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: bots/travel-guide/
    steps:
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.2"
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/R/renv
          key: ${{ runner.os }}-r-4.2.2-renv-${{ hashFiles('./bots/travel-guide/renv.lock') }}
      - name: Restore R packages
        run: |
          install.packages("renv")
          renv::activate()
          renv::restore()
        shell: Rscript {0}
      - name: Run R scripts
        env:
          SHERPA_API_KEY: ${{ secrets.SHERPA_API_KEY }}
        run: Rscript sherpa.R
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache npm packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('./bots/travel-guide/package-lock.json') }}
      - name: Install npm packages
        run: npm ci
      - name: Run Q cli
        run: npm run update-production
        env:
          Q_PRODUCTION_SERVER: ${{ secrets.Q_PRODUCTION_SERVER }}
          Q_PRODUCTION_ACCESSTOKEN: ${{ secrets.Q_PRODUCTION_ACCESSTOKEN }}
          Q_PRODUCTION_ID: 3a9abac92d258dff5f305f2fd069a439
          SHERPA_API_KEY: ${{ secrets.SHERPA_API_KEY }}
          SHERPA_API_URL: requirements-api.joinsherpa.com
      - name: Log failure to slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
